tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#ffdbca",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "tertiary-container": "#6e2d00",
        "on-error-container": "#93000a",
        "surface-tint": "#4059aa",
        "tertiary-fixed-dim": "#ffb690",
        "surface-bright": "#f8f9fa",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#783200",
        "on-tertiary-container": "#ff8f4f",
        "primary-fixed-dim": "#b6c4ff",
        "on-primary-fixed": "#00164e",
        "on-surface": "#191c1d",
        "primary-container": "#1e3a8a",
        "on-primary-fixed-variant": "#264191",
        "on-tertiary": "#ffffff",
        "outline-variant": "#c5c5d3",
        "on-background": "#191c1d",
        "surface-container-highest": "#e1e3e4",
        "on-secondary-container": "#fefcff",
        "surface-variant": "#e1e3e4",
        "on-secondary-fixed": "#001a42",
        "secondary-container": "#2170e4",
        primary: "#00236f",
        "surface-container": "#edeeef",
        background: "#f8f9fa",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "on-surface-variant": "#444651",
        "surface-dim": "#d9dadb",
        "inverse-surface": "#2e3132",
        "error-container": "#ffdad6",
        "secondary-fixed": "#d8e2ff",
        "on-secondary-fixed-variant": "#004395",
        tertiary: "#4b1c00",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-low": "#f3f4f5",
        surface: "#f8f9fa",
        "secondary-fixed-dim": "#adc6ff",
        outline: "#757682",
        "primary-fixed": "#dce1ff",
        secondary: "#0058be",
        "inverse-primary": "#b6c4ff",
        "on-primary-container": "#90a8ff",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#341100",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
};
